export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

// user

export const USER_SET_USER_ID = 'USER_SET_USER_ID';
export const USER_SET_TOKEN = 'USER_SET_TOKEN';
export const USER_GET_USERINFO = 'USER_GET_USERINFO';
export const USER_SET_USERINFO = 'USER_SET_USERINFO';
export const USER_GET_AVATAR = 'USER_GET_AVATAR';
export const USER_SET_AVATAR = 'USER_SET_AVATAR';
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';
export const USER_EXIT = 'USER_EXIT';

// search dialog

export const SEARCH_PENDING = 'SEERCH_PENDING';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const FIND_USER_BY_ID = 'FIND_USER_BY_ID';
export const SET_FINDED_DATA = 'SET_FINDED_DATA';
export const SEARCH_CLEAR_DATA = 'SEARCH_CLEAR_DATA';

// dialog

export const CREATE_DIALOG = 'CREATE_DIALOG';
export const SET_ALL_DIALOGS = 'SET_ALL_DIALOGS';
export const GET_ALL_DIALOGS = 'GET_ALL_DIALOGS';
export const DIALOG_PENDING = 'DIALOG_PENDING';
export const DIALOG_SUCCESS = 'DIALOG_SUCCESS';
export const DIALOG_ERROR = 'DIALOG_ERROR';
export const DIALOG_DELETE_BY_ID = 'DIALOG_DELETE_BY_ID';
export const SET_CURRENT_DIALOG_ID = 'SET_CURRENT_DIALOG_ID';
export const SET_CURRENT_PARTNER = 'SET_CURRENT_PARTNER';
export const SET_PARTNER_ONLINE = 'SET_PARTNER_ONLINE';
export const SET_PARTNER_TYPING = 'SET_PARTNER_TYPING';
export const CLEAR_PARTNER_DATA = 'CLEAR_PARTNER_DATA';

// socket

export const SET_SOCKET_IO_CONNECTION = 'SET_SOCKET_IO_CONNECTION';
